language: python

dist: focal

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry install

script:
  - poetry run pytest
  - poetry run mypy
  - poetry run pylint pytest_insta tests
  - poetry run black --check pytest_insta tests

jobs:
  include:
    - python: 3.8

    - stage: publish
      python: 3.8
      if: tag IS present
      script:
        - poetry build
        - poetry publish --username="__token__" --password="$PYPI_TOKEN"
